vich_uploader:
    db_driver: orm

    mappings:
        products:
           uri_prefix: '%articles_images%'
           upload_destination: '%kernel.project_dir%/public%articles_images'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            
            
